### fnanno.pyの中身

import pandas as pd
# merged_best_hits.txtのパスと読み込み
merged_best_hits_file = 'merged_best_hits.txt'
merged_df = pd.read_csv(merged_best_hits_file, sep='\t')

#出力ファイルのパス
output_file = 'merged_with_gene_function.csv'
output_file2 = 'merged_with_gene_function.txt'

##########################################################
###Dmel
# Dmel_protein.faaのパス
dmel_protein_file = '/home/kosukesano/reference_sequence/functional_annotation/Dmel_protein.faa'

# 遺伝子IDと遺伝子機能を抽出するリスト
gene_ids = []
gene_functions = []

# Dmel_protein.faaファイルを読み込み、ヘッダー行から情報を抽出
with open(dmel_protein_file, 'r') as file:
    for line in file:
        if line.startswith('>'):
            parts = line.strip().split(' ', 1)
            gene_id = "Dmel_" + parts[0][1:]  # ">"を取り除き、"Dmel_"を追加
            parts2 = parts[1].split(' [')
            gene_function = parts2[0]  # 遺伝子機能
            gene_ids.append(gene_id)
            gene_functions.append(gene_function)

# 遺伝子IDと遺伝子機能のデータフレームを作成
data = {'GeneID': gene_ids, 'GeneFunction': gene_functions}
df = pd.DataFrame(data)

# マージ
merged_df = pd.merge(
    merged_df,
    df,
    left_on='Dmelanogaster',
    right_on='GeneID',
    how='left'
)

# 不要なGeneID列を削除し、列名をDmel_GeneFunctionに変更
merged_df = merged_df.drop(columns=['GeneID'])
merged_df = merged_df.rename(columns={'GeneFunction': 'Dmel_GeneFunction'})

# 確認のため最初の数行を表示
print("Dmel")
print(merged_df)
####################################################################
###Ecol

# Ecol_protein.faaのパス
Ecol_protein_file = '/home/kosukesano/reference_sequence/functional_annotation/Ecol_protein.faa'

# 遺伝子IDと遺伝子機能を抽出するリスト
gene_ids = []
gene_functions = []

# Ecol_protein.faaファイルを読み込み、ヘッダー行から情報を抽出
with open(Ecol_protein_file, 'r') as file:
    for line in file:
        if line.startswith('>'):
            parts = line.strip().split(' ', 1)
            gene_id = "Ecol_" + parts[0][1:]  # ">"を取り除き、"Ecol_"を追加
            parts2 = parts[1].split(' [')
            gene_function = parts2[0]  # 遺伝子機能
            gene_ids.append(gene_id)
            gene_functions.append(gene_function)

# 遺伝子IDと遺伝子機能のデータフレームを作成
data = {'GeneID': gene_ids, 'GeneFunction': gene_functions}
df = pd.DataFrame(data)

# マージ
merged_df = pd.merge(
    merged_df,
    df,
    left_on='Ecoli',
    right_on='GeneID',
    how='left'
)

# 不要なGeneID列を削除し、列名をEcol_GeneFunctionに変更
merged_df = merged_df.drop(columns=['GeneID'])
merged_df = merged_df.rename(columns={'GeneFunction': 'Ecol_GeneFunction'})

# 確認のため最初の数行を表示
print("Ecol")
print(merged_df)
####################################################################
###Tcas

# Tcas_protein.faaのパス
Tcas_protein_file = '/home/kosukesano/reference_sequence/functional_annotation/Tcas_protein.faa'

# 遺伝子IDと遺伝子機能を抽出するリスト
gene_ids = []
gene_functions = []

# Tcas_protein.faaファイルを読み込み、ヘッダー行から情報を抽出
with open(Tcas_protein_file, 'r') as file:
    for line in file:
        if line.startswith('>'):
            parts = line.strip().split(' ', 1)
            gene_id = "Tcas_" + parts[0][1:]  # ">"を取り除き、"Tcas_"を追加
            parts2 = parts[1].split(' [')
            gene_function = parts2[0]  # 遺伝子機能
            gene_ids.append(gene_id)
            gene_functions.append(gene_function)

# 遺伝子IDと遺伝子機能のデータフレームを作成
data = {'GeneID': gene_ids, 'GeneFunction': gene_functions}
df = pd.DataFrame(data)

# マージ
merged_df = pd.merge(
    merged_df,
    df,
    left_on='Tcastaneum',
    right_on='GeneID',
    how='left'
)

# 不要なGeneID列を削除し、列名をTcas_GeneFunctionに変更
merged_df = merged_df.drop(columns=['GeneID'])
merged_df = merged_df.rename(columns={'GeneFunction': 'Tcas_GeneFunction'})

# 確認のため最初の数行を表示
print("Tcas")
print(merged_df)
####################################################################
###Sory

# Sory_protein.faaのパス
Sory_protein_file = '/home/kosukesano/reference_sequence/functional_annotation/Sory_protein.faa'

# 遺伝子IDと遺伝子機能を抽出するリスト
gene_ids = []
gene_functions = []

# Sory_protein.faaファイルを読み込み、ヘッダー行から情報を抽出
with open(Sory_protein_file, 'r') as file:
    for line in file:
        if line.startswith('>'):
            parts = line.strip().split(' ', 1)
            gene_id = "Sory_" + parts[0][1:]  # ">"を取り除き、"Sory_"を追加
            parts2 = parts[1].split(' [')
            gene_function = parts2[0]  # 遺伝子機能
            gene_ids.append(gene_id)
            gene_functions.append(gene_function)

# 遺伝子IDと遺伝子機能のデータフレームを作成
data = {'GeneID': gene_ids, 'GeneFunction': gene_functions}
df = pd.DataFrame(data)

# マージ
merged_df = pd.merge(
    merged_df,
    df,
    left_on='Soryzae',
    right_on='GeneID',
    how='left'
)

# 不要なGeneID列を削除し、列名をSory_GeneFunctionに変更
merged_df = merged_df.drop(columns=['GeneID'])
merged_df = merged_df.rename(columns={'GeneFunction': 'Sory_GeneFunction'})

# 確認のため最初の数行を表示
print("Sory")
print(merged_df)
#########################################################

merged_df_with_function = merged_df.reindex(columns=['Madara',\
 'Ecoli','Ecol_GeneFunction',\
 'Dmelanogaster', 'Dmel_GeneFunction',\
  'Tcastaneum', 'Tcas_GeneFunction',\
   'Soryzae', 'Sory_GeneFunction'])

# 新しいデータフレームをCSVファイルとして保存
merged_df_with_function.to_csv(output_file, index=False)

# 新しいデータフレームをTXTファイルとして保存
merged_df_with_function.to_csv(output_file2, sep='\t', index=False)  # タブ文字を区切り文字として使用

# 確認のため最初の数行を表示
print(merged_df_with_function)