	
#$ -S /bin/bash
#$ -cwd
#$ -l gpu
#$ -pe def_slot 6



# ディレクトリパス
input_dir="/home/kosukesano/tools/for_paml/250210_tRNA/SCO_CDS/"
output_dir="/home/kosukesano/tools/for_paml/250210_tRNA/PRANK_CDS/"


# 各ファイルに対してアラインメントを実行
for file in "$input_dir"*.fna; do
  # 元のファイル名から拡張子を除いたものを取得
  base_name=$(basename "$file" .fna)

  # 出力ファイル名を生成
  output_file="${output_dir}${base_name}_pranked.fna"

  # prankを実行
  singularity exec -e /usr/local/biotools/p/prank\:v.170427--h9f5acd7_6 prank -d="$file" -o="$output_file" -codon -F -threads=4

  echo "Aligned file created: $output_file"
done