---
title: "卒業研究Method"
author: "佐野孔亮"
format: 
  html: 
    embed-resources: true
    toc: true
---

# ゲノムデータのソフトマスキング
ゲノムの塩基配列データには反復配列やトランスポゾンなどの配列が含まれており、それらは進化解析の際にノイズとなる。このような配列を後々の解析で除外するため、予め小文字に置換する必要がある。今回は`EDTA`パイプラインに`Dfam`の反復配列データベースを統合することで、高精度なソフトマスクを実施した。

まず、`EDTA`パイプラインを使用し、対象のゲノムデータからde novoで反復配列のBLASTデータベースを作成した。以下のコマンドを用いた。
```bash
BuildDatabase -name DATABASE GENOME.fasta
```

続いて、`EDTA`パイプラインの`RepeatModeler`を使用し、BLASTデータベースを元に反復配列を抽出した。以下のコマンドを用いた。
```bash
RepeatModeler -database DATABASE -pa 12
```

続いて、上記出力の`consensi.fa.classified`と`Dfam`データベースの`RepeatMasker`用反復配列ライブラリを結合した。以下のコマンドを用いた。
```bash
cat Dfam-RepeatMasker.lib consensi.fa.classified > merged.lib
```

結合したライブラリを参照し、`RepeatMasker`ツールで対象となるゲノムデータの反復配列をソフトマスキングした。なお`EDTA`パイプラインの`RepeatMasker`はバージョンが`4.1.2-p1`と若干古かったため、`Docker`コンテナにパッケージングされている`4.1.7-p1`の`RepeatMasker`を別途インストールし、そちらを用いて解析を行った。
```bash
RepeatMasker -pa 12 -lib merged.lib -xsmall -gff GENOME.fasta
```

# ゲノムデータの構造アノテーション

進化解析にはゲノム中の遺伝子構造の情報が必要不可欠だが、ソフトマスクしたゲノムデータには遺伝子構造の情報が付加されていない。今回は`BRAKER3`パッケージを用いてこれら遺伝子構造を予測した。`BRAKER3`は過去の研究から得られた遺伝子構造アノテーションでトレーニングされた統計モデルと、トランスクリプトームデータを元にした遺伝子発現部位の情報を元に遺伝子構造をde novoで予測するツールである。<br>
以下のコマンドを用いて実行した。
```bash
braker.pl --genome=GENOME_masked.fasta\
        --prot_seq=/Arthropoda.fa\
        --rnaseq_sets_ids=rnaseq_data\
        --rnaseq_sets_dir=/path/to/rnaseq/data/dir\
        --threads=16\
        --species=species_name\
        --AUGUSTUS_CONFIG_PATH=/path/to/augustus/config\
        --AUGUSTUS_BIN_PATH=/path/to/usr/bin\
        --AUGUSTUS_SCRIPTS_PATH=/path/to/augustus/scripts\
        --GENEMARK_PATH=/path/to/GeneMark-ETP/bin\
        --PROTHINT_PATH=/path/to/ProtHint/bin\
        --TSEBRA_PATH=/path/to/TSEBRA/bin
```
`ProtHint`用のタンパク質配列データは`OrthoDB`のArthropodaのデータセットを用いた。また、RNA-seqのデータは我々のグループが過去に調査したデータを用いた。

# アイソフォームの除去
`BRAKER3`によって予測された遺伝子には、スプライシングバリアントなどのアイソフォームが複数含まれている。これらのアイソフォームは今後の進化解析においてオーソログ推定を行う際のノイズとなる。今回は各遺伝子に含まれるアイソフォームのうち、配列長が最大のもののみを代表値として抽出する処理を`fasp`というツールを用いて行った。<br>
以下のスクリプトを実行した。

```bash
#!/usr/bin/env python3

"""Library for processing protein FASTA files.

Functions
---------
exclude_isoforms_by_length: Exclude isoforms based on length.
exclude_non_nuclear_proteins: Exclude mitochondrial and chloroplast proteins.

"""

from Bio import SeqIO

def exclude_isoforms_by_length(input_filename: str, output_filename: str, gff3_file: str) -> None:
    """Exclude isoforms based on length.
    
    Args
    ----
    input_filename : str
        Input protein FASTA filename.
    output_filename : str
        Output protein FASTA filename.
    gff3_file : str
        Input genome GFF3 filename.

    """
    
    def parse_gff3(gff3_file: str) -> dict:
        """Parse GFF3 file and make dict with 'protein_id', 'start', 'end' and 'length' of each gene. 

        Args
        ----
        gff3_file : str

        Returns
        -------
        genes : dict
            Dict with 'protein_id', 'start', 'end' and 'length' of each genes. 

        """
        genes = {}
        with open(gff3_file, "r") as gff3_handle:
            for line in gff3_handle:
                ## Exclude comments
                if line.startswith("#"):
                    continue

                li = line.strip().split("\t")
                if len(li) != 9:
                    continue
                ptg_num, tools, kind, start, end, score, strand, phase, attributes = li

                ## Exclude lines other than CDS.
                if kind != "CDS":
                    continue

                ## Handle attributes.
                attr_dict = {}
                for attr in attributes.split("; "):
                    key_value = attr.split(" ")
                    ##print(len(key_value))
                    if len(key_value) != 2:
                        continue
                    key, value = key_value
                    attr_dict[key] = value
                
                ## Exclude CDS without protein_id.
                if "transcript_id" not in attr_dict:
                    print("trans")
                    continue

                ## Exclude CDS without protein_id.
                if "gene_id" not in attr_dict:
                    print("gene_ID")
                    continue

                ## Read information of CDS.
                protein_id = attr_dict["transcript_id"]
                protein_id = protein_id.strip('"')
                print(protein_id)
                if "gene_id" in attr_dict:
                    gene = attr_dict["gene_id"]
                start, end, length = int(start), int(end), int(end) - int(start)
                if gene not in genes:
                    genes[gene] = []
                genes[gene].append({"protein_id": protein_id, "start": start, "end": end, "length": length})

        return genes

    def select_longest_protein(genes: dict) -> dict:
        """Select the longest proteins for each gene based on CDS information.

        Args
        ----
        genes : dict

        Returns
        -------
        longest_proteins : dict

        """
        longest_proteins = {}
        for gene, cds_list in genes.items():
            protein_lengths = {}
            for cds in cds_list:
                protein_id = cds["protein_id"]
                length = cds["length"]
                if protein_id not in protein_lengths:
                    protein_lengths[protein_id] = length
                else:
                    protein_lengths[protein_id] += length
            ## Select the longest protein.
            longest_proteins[gene] = max(protein_lengths, key=protein_lengths.get)

        return longest_proteins

    def slice_proteins(input_filename: str, output_filename: str, longest_proteins: dict) -> None:
        """Slice FASTA file to retain only the longest proteins for each gene.

        Args
        ----
        input_filename : str
        output_filename : str
        longest_proteins : dict

        """
        input_proteins = SeqIO.to_dict(SeqIO.parse(input_filename, "fasta"))
        selected_protein_ids = set(longest_proteins.values())

        output_proteins = []
        for selected_protein_id in selected_protein_ids:
            if selected_protein_id not in input_proteins:
                continue
            output_proteins.append(input_proteins[selected_protein_id])
        
        with open(output_filename, "w") as output_handle:
            SeqIO.write(output_proteins, output_handle, "fasta")

    genes = parse_gff3(gff3_file)
    longest_proteins = select_longest_protein(genes)
    slice_proteins(input_filename, output_filename, longest_proteins)


exclude_isoforms_by_length("braker/braker.aa", "241129_madara_iso1.aa", "braker/braker.gtf")
```


